pull_request_rules:
- name: auto-merge
  description: >
    Automatic merge of PRs to main
  conditions:
    - "#approved-reviews-by>=2"
    - "#review-requested=0"
    - "#changes-requested-reviews-by=0"
    - base=main
    - label!=do-not-merge
    - label!=needs-rebase
    - check-success=pre-commit
    - check-success=title-check

    # Check redhat-distro-container job only when relevant paths are changed
    - or:
      - and:
        - check-success=build-test-push
        - or:
          - files~=^\.github/actions/setup-vllm/action\.yml$
          - files~=^\.github/workflows/redhat-distro-container\.yml$
          - files~=^distribution/
          - files~=^tests/
      - and:
        - -files~=^\.github/actions/setup-vllm/action\.yml$
        - -files~=^\.github/workflows/redhat-distro-container\.yml$
        - -files~=^distribution/
        - -files~=^tests/

  actions:
    merge:
      method: merge
      commit_message_template: |
        {{ title }} (#{{ number }})

        {{ body }}

        {% for user in approved_reviews_by %}
        Approved-by: {{ user }}
        {% endfor %}
    delete_head_branch:

- name: ping author on conflicts and add 'needs-rebase' label
  conditions:
      - conflict
      - -closed
  actions:
    label:
      add:
        - needs-rebase
    comment:
      message: >
       This pull request has merge conflicts that must be resolved before it
       can be merged. @{{author}} please rebase it.
       https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

- name: remove 'needs-rebase' label when conflict is resolved
  conditions:
      - -conflict
      - -closed
  actions:
    label:
      remove:
        - needs-rebase
