FROM registry.access.redhat.com/ubi9/python-312@sha256:95ec8d3ee9f875da011639213fd254256c29bc58861ac0b11f290a291fa04435
WORKDIR /opt/app-root

RUN pip install sqlalchemy # somehow sqlalchemy[asyncio] is not sufficient
{dependencies}
RUN pip install --no-cache llama-stack==0.2.23
{llama_stack_install_source}
RUN mkdir -p ${{HOME}}/.llama ${{HOME}}/.cache
COPY distribution/run.yaml ${{APP_ROOT}}/run.yaml

ENTRYPOINT ["llama", "stack", "run", "/opt/app-root/run.yaml"]
